#!/usr/bin/env python3
"""
core/strategy_map.py — 策略映射表
===================================
统一管理所有策略的选股逻辑映射。

设计理念：
- 回测和模拟盘共享同一套选股逻辑
- 通过 strategy name 映射到具体的选股函数
- 新增策略只需在此表注册，不需要改账户脚本
- 策略与账户解耦：账户在 DB 中绑定策略，不在代码里硬编码

使用方式:
    from core.strategy_map import STRATEGY_MAP, load_strategy
    strategy = load_strategy("v27")
    factors = strategy["calc_factors"](close_panel, volume_panel, amount_panel, high_panel, low_panel, open_panel)
    cands = strategy["select_stocks"](factors, date)
"""
import importlib

def _load_func(dotted_path):
    """动态加载函数：module.path.func_name"""
    parts = dotted_path.rsplit(".", 1)
    if len(parts) != 2:
        raise ValueError(f"无效路径: {dotted_path}")
    mod = importlib.import_module(parts[0])
    return getattr(mod, parts[1])


def load_strategy(name):
    """加载策略配置"""
    s = STRATEGY_MAP.get(name)
    if s is None:
        raise ValueError(f"未知策略: {name}，可用: {list(STRATEGY_MAP.keys())}")
    # 动态加载函数（如需）
    result = dict(s)
    # 默认股票池：zz1800（zz800是子集，通过 pool='zz800' 显式指定）
    result.setdefault("pool", "zz1800")
    if "select_fn" in result:
        result["select_stocks"] = _load_func(result["select_fn"])
    if "calc_factors_fn" in result:
        result["calc_factors"] = _load_func(result["calc_factors_fn"])
    return result


def list_strategy_names():
    """列出所有可用策略名"""
    return list(STRATEGY_MAP.keys())


STRATEGY_MAP = {
    # ── v11b: Ensemble 截面因子 ──
    "v11b": {
        "mode": "custom",
        "description": "Ensemble 截面因子选股（Momentum+Volatility+Reversal 3组并集）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v11b_select.select_stocks",
        "calc_factors_fn": "scripts.strategies.v11b_select.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "MAX_HOLDINGS": 12,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.30,
            "HOLD_DAYS_MAX": 5,
            "REBAL_FREQ": 5,
            "TOP_N": 8,
        },
    },

    # ── v27: 价量共振动量 ──
    "v27": {
        "mode": "custom",
        "description": "价量共振动量（mom_5>2% + pv_corr_20 + gap/illiq/boll）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v27_select.select_stocks_v27",
        "calc_factors_fn": "scripts.strategies.v27_select.calc_factors",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MOM_THRESHOLD": 0.05,
        },
    },

    # ── v28: Kronos AI 增强（v27 + 预测因子）──
    "v28": {
        "mode": "custom",
        "description": "Kronos AI 增强选股（v27初筛 + kronos_ret/conf/trend二次排序）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v28_kronos.select_stocks_v28",
        "calc_factors_fn": "scripts.strategies.v28_kronos.calc_factors",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "MAX_HOLDINGS": 12,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.25,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 2,
            "MOM_THRESHOLD": 0.05,
            "KRONOS_ENABLED": True,
            "KRONOS_ALPHA": 0.5,
            "KRONOS_CANDIDATE_N": 50,
            "KRONOS_PRED_LEN": 5,
            "KRONOS_LOOKBACK": 200,
            "KRONOS_T": 0.8,
            "KRONOS_TOP_P": 0.85,
            "KRONOS_SAMPLE_COUNT": 5,
            "KRONOS_DEVICE": "cpu",
            "KRONOS_MODEL": "small",
            "KRONOS_CONF_THRESHOLD": 0.3,
        },
    },

    # ── v20c: 尾盘缩量企稳（已退役）──
    # 面板顺序 bug 修复后策略失效（WF 5/16，全量 -67%，核心因子 IC≈0）
    # 代码保留在 scripts/strategies/v20_tail_pick.py，不参与活跃交易
    "v20c": {
        "mode": "custom",
        "description": "尾盘缩量企稳（软约束评分排序）— 已退役",
        "timing": "tail",
        "select_fn": "scripts.strategies.v20_tail_pick.select_stocks_tail_pick",
        "calc_factors_fn": "scripts.strategies.v20_tail_pick.calc_tail_pick_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.15,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 8,
            "MAX_POSITION": 0.30,
            "HOLD_DAYS_MAX": 2,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "REGIME_ENABLED": True,
            "REGIME_MA_PERIOD": 20,
            "REGIME_SLOPE_DAYS": 5,
            "REGIME_BULL_ALLOC": 1.0,
            "REGIME_SIDEWAYS_ALLOC": 0.7,
            "REGIME_BEAR_ALLOC": 0.3,
        },
    },

    # ── v33: 残差动量 ──
    "v33": {
        "mode": "custom",
        "description": "残差动量（剥离市场Beta后的个股alpha信号）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v33_residual_momentum.select_stocks_v33",
        "calc_factors_fn": "scripts.strategies.v33_residual_momentum.calc_factors",
        "params": {
            "STOP_LOSS": -0.02,
            "TAKE_PROFIT": 0.05,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "RESID_WINDOW": 12,
            "RESID_LOOKBACK": 6,
            "RESID_SKIP": 1,
            "MIN_OBS": 6,
            "MOM_THRESHOLD": 0.0,
            "REGIME_ENABLED": True,
            "REGIME_MA_PERIOD": 20,
            "REGIME_SLOPE_DAYS": 5,
            "REGIME_BULL_ALLOC": 1.0,
            "REGIME_SIDEWAYS_ALLOC": 0.7,
            "REGIME_BEAR_ALLOC": 0.3,
        },
    },

    # ── v35: 行业轮动（市值分组代理行业）──
    "v35": {
        "mode": "custom",
        "description": "行业轮动选股（大盘/中/小盘分组动量 + 个股动量加权）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v35_sector_rotation.select_stocks_v35",
        "calc_factors_fn": "scripts.strategies.v35_sector_rotation.calc_factors",
        "params": {
            "STOP_LOSS": -0.02,
            "TAKE_PROFIT": 0.05,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "SECTOR_MOM_WEIGHT": 0.30,
            "SECTOR_SHORT": 5,
            "SECTOR_MID": 20,
            "SECTOR_LONG": 60,
            "SECTOR_W_SHORT": 0.4,
            "SECTOR_W_MID": 0.3,
            "SECTOR_W_LONG": 0.3,
            "MOM_THRESHOLD": 0.01,
            "REGIME_ENABLED": True,
            "REGIME_MA_PERIOD": 20,
            "REGIME_SLOPE_DAYS": 5,
            "REGIME_BULL_ALLOC": 1.0,
            "REGIME_SIDEWAYS_ALLOC": 0.7,
            "REGIME_BEAR_ALLOC": 0.3,
        },
    },

    # ── v32: 分析师预期因子 ──
    "v32": {
        "mode": "custom",
        "description": "分析师预期因子（SUE代理+盈利预测上调+异常覆盖+综合因子）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v32_analyst_expectation.select_stocks_v32",
        "calc_factors_fn": "scripts.strategies.v32_analyst_expectation.calc_factors",
        "params": {
            "STOP_LOSS": -0.02,
            "TAKE_PROFIT": 0.05,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "ANALYST_WEIGHT": 0.30,
            "SUE_THRESHOLD": 0.0,
            "FORECAST_UP_THRESHOLD": 0.10,
            "ANALYST_COVERAGE_MIN": 5,
            "REGIME_ENABLED": True,
            "REGIME_MA_PERIOD": 20,
            "REGIME_SLOPE_DAYS": 5,
            "REGIME_BULL_ALLOC": 1.0,
            "REGIME_SIDEWAYS_ALLOC": 0.7,
            "REGIME_BEAR_ALLOC": 0.3,
        },
    },

    # ── v31: 价量共振+动量增强（已归档，与 v27 高度重复）──
    # mom_20/mom_40 与 mom_5 相关性 0.3-0.5，非独立信息，预期选股重叠度 >70%
    # 代码保留在 scripts/strategies/v29_select.py，不参与活跃交易
    "v31": {
        "mode": "custom",
        "description": "价量共振+动量增强（v27核心85% + mom_20/mom_40动量15%）— 已归档，与v27高度重复",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v29_select.select_stocks_v29",
        "calc_factors_fn": "scripts.strategies.v29_select.calc_factors",
        "archived": True,
        "archive_reason": "与 v27 因子高度重叠（mom_20/mom_40 与 mom_5 相关性 0.3-0.5），无独立回测价值",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MOM_THRESHOLD": 0.05,
            "MOM_20_WEIGHT": 0.15,
            "MOM_40_WEIGHT": 0.15,
        },
    },
    # ── v39c: 多因子评分版（v27 选股门槛 + 7因子加权评分）──
    "v39c": {
        "mode": "custom",
        "description": "多因子评分（v27选股门槛 + 7因子加权评分，W_MOM=0.20 W_PV_CORR=0.05）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39c_pv_resonance.select_stocks_v39c",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.20,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.10,
            "W_SIZE": 0.10,
            "W_FUND_FLOW": 0.15,
            "W_GAP": 0.10,
            "W_ILLIQ": 0.10,
        },
    },

    # ── v40: 因子恶化卖出 + 延迟止盈止损（v39c 评分体系 + 持仓重评分）──
    "v40": {
        "mode": "custom",
        "description": "因子恶化卖出（持仓评分<SELL_THRESHOLD卖出，>BUY_BACK_THRESHOLD延迟止盈止损）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v40_factor_exit.select_stocks_v40",
        "calc_factors_fn": "scripts.strategies.v40_factor_exit.calc_factors",
        "factor_exit_fn": "scripts.strategies.v40_factor_exit.check_factor_exit",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.20,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.10,
            "W_SIZE": 0.10,
            "W_FUND_FLOW": 0.15,
            "W_GAP": 0.10,
            "W_ILLIQ": 0.10,
            # v40 新增
            "SELL_THRESHOLD": 0.35,
            "BUY_BACK_THRESHOLD": 0.65,
            "SELL_PENALTY_N": 1,
            "SELL_MODE": "momentum",
            "MOMENTUM_DROP_PCT": 0.20,
        },
    },

    # ── v40b: 纯轮动（每日卖最低4只+买最高4只，无硬风控）──
    "v40b": {
        "mode": "custom",
        "description": "纯轮动（每日卖出持仓评分最低4只+买入全市场评分最高4只，无硬风控）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v40_factor_exit.select_stocks_v40b",
        "calc_factors_fn": "scripts.strategies.v40_factor_exit.calc_factors",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.20,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.10,
            "W_SIZE": 0.10,
            "W_FUND_FLOW": 0.15,
            "W_GAP": 0.10,
            "W_ILLIQ": 0.10,
            # v40b 新增
            "SELL_COUNT": 4,
            "BUY_COUNT": 4,
            "NO_HARD_RISK": True,
        },
    },

    # ── v41: VWAP 偏离 + 净支撑量因子（v39c 评分体系 + 2个新量价因子）──
    "v41": {
        "mode": "custom",
        "description": "VWAP偏离+净支撑量因子（v39c 7因子 + VWAP_DEV 0.15 + NET_SUPPORT 0.10）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v41_vwap_deviation.select_stocks_v41",
        "calc_factors_fn": "scripts.strategies.v41_vwap_deviation.calc_factors_v41",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "COOLDOWN_DAYS": 0,
            "MAX_HOLDINGS": 8,
            # v39c 原有权重
            "W_MOM": 0.20,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.10,
            "W_SIZE": 0.10,
            "W_FUND_FLOW": 0.15,
            "W_GAP": 0.10,
            "W_ILLIQ": 0.10,
            # 新增因子权重
            "W_VWAP_DEV": 0.15,
            "W_NET_SUPPORT": 0.10,
        },
    },

    # ── v39d: 参数优化版（基于 IC 分析调整权重 + 风控参数）──
    "v39d": {
        "mode": "custom",
        "description": "v39c 参数优化（IC 驱动权重调整 + 松风控 + 低换手）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39d_optimized.select_stocks_v39d",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.15,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.30,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v39e: 基于 v39d 交易行为分析进一步优化 ──
    "v39e": {
        "mode": "custom",
        "description": "v39d 交易行为优化（收紧止损 + 缩短持有期 + 降仓位 + size_factor 40%）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39e_optimized.select_stocks_v39e",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.03,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.05,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.15,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.10,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.40,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v39f: 修正 v39e 错误（保持 -5% 止损 + 降低止盈到 5%）──
    "v39f": {
        "mode": "custom",
        "description": "v39e 修正（保持松止损 + 低止盈 + 高换手）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39f_optimized.select_stocks_v39f",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.10,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.40,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v39g: 风控参数优化（短持有期 + 低止盈 + 高换手）──
    "v39g": {
        "mode": "custom",
        "description": "v39g 风控优化（HOLD_DAYS_MAX=3 + TAKE_PROFIT=5% + MAX_DAILY_BUY=4）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39g_optimized.select_stocks_v39g",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.10,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.40,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v66: 连续两天涨停情绪因子（v39g + 两日涨停加分）──
    "v66": {
        "mode": "custom",
        "description": "v66 连续两天涨停情绪因子（v39g + W_TWO_DAY_LIMIT=0.35）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v66_two_day_limit.select_stocks_v66",
        "calc_factors_fn": "scripts.strategies.v66_two_day_limit.calc_factors_v66",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.08,
            "W_PV_CORR": 0.04,
            "W_TURNOVER": 0.04,
            "W_SIZE": 0.35,
            "W_FUND_FLOW": 0.04,
            "W_GAP": 0.04,
            "W_ILLIQ": 0.16,
            "W_TWO_DAY_LIMIT": 0.35,
        },
    },

    # ── v67: v66 + 情绪择时 ──
    "v67": {
        "mode": "custom",
        "description": "v67: v66 + 情绪择时（市场情绪>阈值时才交易）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v67.select_stocks_v67",
        "calc_factors_fn": "scripts.strategies.v67.calc_factors_v67",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "W_MOM": 0.08,
            "W_PV_CORR": 0.04,
            "W_TURNOVER": 0.04,
            "W_SIZE": 0.35,
            "W_FUND_FLOW": 0.04,
            "W_GAP": 0.04,
            "W_ILLIQ": 0.16,
            "W_TWO_DAY_LIMIT": 0.35,
            "SENTIMENT_THRESHOLD": 2.0,
            "SENTIMENT_WINDOW": 15,
            "EXCLUDE_LIMIT_UP": True,  # 涨停过滤开关：True=排除涨停股，False=不排除
        },
    },
    # ── v68: v67降低低流动性权重+加大动量权重 ──
    "v68": {
        "mode": "custom",
        "description": "v68: v67基础上弱化低流动性偏好，强化动量驱动",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v68.select_stocks_v68",
        "calc_factors_fn": "scripts.strategies.v68.calc_factors_v68",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "W_MOM": 0.35,
            "W_PV_CORR": 0.02,
            "W_TURNOVER": 0.03,
            "W_SIZE": 0.35,
            "W_FUND_FLOW": 0.00,
            "W_GAP": 0.00,
            "W_ILLIQ": 0.05,
            "W_RECENT_LIMIT_3D": 0.0,  # 新因子：3天内涨停过（默认0，待回测调优）
            "SENTIMENT_THRESHOLD": 2.0,
            "SENTIMENT_WINDOW": 15,
            "EXCLUDE_LIMIT_UP": True,
        },
    },

    # ── v69: 行业动量追涨 ──
    "v69": {
        "mode": "custom",
        "description": "v69: 行业动量追涨（申万行业分类+个股动量+情绪择时）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v69_industry_momentum.select_stocks_v69",
        "calc_factors_fn": "scripts.strategies.v69_industry_momentum.calc_factors_v69",
        "params": {
            "STOP_LOSS": -0.06,
            "TAKE_PROFIT": 0.12,
            "HOLD_DAYS_MAX": 5,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 5,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "W_MOM_5D": 0.50,
            "W_MOM_10D": 0.30,
            "W_MOM_20D": 0.20,
            "TOP_INDUSTRY_PCT": 0.20,
            "TOP_INDUSTRIES": 3,
            "W_STOCK_MOM": 0.50,
            "W_STOCK_VOL": 0.30,
            "W_STOCK_AMT": 0.20,
            "STOCK_MOM_MIN": 0.02,
            "SENTIMENT_ENABLED": True,
            "SENTIMENT_THRESHOLD": 20,
            "EXCLUDE_LIMIT_UP": True,
            "MIN_AMOUNT": 5e7,
        },
    },
    # ── v71: 极端集中动量 ──
    "v71": {
        "mode": "custom",
        "description": "v71: 极端集中动量（Top1行业+1-2只强势股+指数MA）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v71_extreme_momentum.select_stocks_v71",
        "calc_factors_fn": "scripts.strategies.v71_extreme_momentum.calc_factors_v71",
        "params": {
            "STOP_LOSS": -0.03,
            "TAKE_PROFIT": 0.20,
            "HOLD_DAYS_MAX": 3,
            "MAX_DAILY_BUY": 1,
            "MAX_POSITION": 0.40,
            "MAX_HOLDINGS": 3,
            "HOLD_DAYS_MIN": 1,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "TOP_INDUSTRIES": 1,
            "STOCK_MOM_MIN": 0.05,
            "SENTIMENT_ENABLED": True,
            "SENTIMENT_THRESHOLD": 15,
            "EXCLUDE_LIMIT_UP": True,
        },
    },


    # ── v72: 首板低开修复 ──
    "v72": {
        "mode": "custom",
        "description": "v72: 首板低开修复（昨日首板涨停+今日低开+修复交易）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v72_low_open_repair.select_stocks_v72",
        "calc_factors_fn": "scripts.strategies.v72_low_open_repair.calc_factors_v72",
        "params": {
            "STOP_LOSS": -0.03,
            "TAKE_PROFIT": 0.08,
            "HOLD_DAYS_MAX": 3,
            "MAX_DAILY_BUY": 1,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "HOLD_DAYS_MIN": 1,
            "LOW_OPEN_MAX": 1.01,
            "LOW_OPEN_MIN": 0.95,
            "EXCLUDE_LIMIT_UP": True,
            "MIN_AMOUNT": 5e7,
        },
    },


    # ── v73: ETF动量轮动 ──
    "v73": {
        "mode": "custom",
        "description": "v73: ETF动量轮动（25日对数回归×R²评分，每次持1只最强ETF）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v73_etf_rotation.select_stocks_v73",
        "calc_factors_fn": "scripts.strategies.v73_etf_rotation.calc_factors_v73",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.15,
            "HOLD_DAYS_MAX": 10,
            "MAX_HOLDINGS": 1,
            "MAX_DAILY_BUY": 1,
            "MAX_POSITION": 1.0,
            "MOM_WINDOW": 25,
            "MOM_MIN_R2": 0.3,
            "INDEX_MA_ENABLED": True,
            "INDEX_MA_PERIOD": 20,
        },
    },

    # ── v39h: 动态 MOM_THRESHOLD（熊市自适应减仓）──
    # ── v39h: 动态 MOM_THRESHOLD（熊市自适应减仓）──
    # ── v39h: 动态 MOM_THRESHOLD（熊市自适应减仓）──
    "v39h": {
        "mode": "custom",
        "description": "v39h 动态门槛（熊市 MOM_THRESHOLD=0.10 自然减仓 + v39d 风控参数）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39h_optimized.select_stocks_v39h",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "MOM_THRESHOLD_BEAR": 0.10,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.15,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.30,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v39i: 最优阈值（夏普 1.199 / 回撤 16.69%）──
    "v39i": {
        "mode": "custom",
        "description": "v39i 最优阈值（BULL=0.05/BEAR=0.08，夏普1.199/回撤16.69%）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39i_optimized.select_stocks_v39i",
        "calc_factors_fn": "scripts.strategies.v39c_pv_resonance.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.05,
            "MOM_THRESHOLD_BEAR": 0.08,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.15,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.30,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v42: 换手率因子研究（v39i + turnover_rate）──
    "v42": {
        "mode": "custom",
        "description": "换手率因子研究（真实换手率 vs 量比，W_TURNOVER_RATE=0.05）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v42_turnover_research.select_stocks_v42",
        "calc_factors_fn": "scripts.strategies.v42_turnover_research.calc_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.05,
            "MOM_THRESHOLD_BEAR": 0.08,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.15,
            "W_PV_CORR": 0.05,
            "W_TURNOVER_RATE": 0.05,
            "W_TURNOVER_AVG": 0.05,
            "W_SIZE": 0.30,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },
    # ── v44: 资金流+动量+低波质量 ──
    "v44": {
        "mode": "custom",
        "description": "资金流+动量质量（W_FLOW=0.35资金流+W_MOM=0.25动量+低波过滤，zz800范围）",
        "timing": "daily",
        "select_fn": "scripts.strategies.v44_flow_momentum.select_stocks_v44",
        "calc_factors_fn": "scripts.strategies.v44_flow_momentum.calc_factors",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.20,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 7,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MARKET_CAP_MIN": 0,
            "MARKET_CAP_MAX": float('inf'),
            "EXCLUDE_ST": True,
            "EXCLUDE_NEW": True,
            "EXCLUDE_LIMIT_UP": True,
            "EXCLUDE_SUSPENDED": True,
            "REBALANCE_DAY": "daily",
            "MONTHS_EMPTY": [],
            "W_FLOW": 0.35,
            "W_MOM": 0.25,
            "W_SIZE": 0.15,
            "W_TURNOVER": 0.10,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.10,
            "VOLATILITY_PERIOD": 20,
            "VOLATILITY_MAX": 0.04,
            "FLOW_CLIP_MAX": 3.0,
            "MOM_THRESHOLD": 0.03,
            "TURNOVER_CLIP_MAX": 0.05,
            "SIZE_CLIP_MAX": 5e10,
        },
    },

    # ── v46: 行业ETF动量轮动 ──
    "v46": {
        "mode": "custom",
        "description": "行业ETF动量轮动（23只行业ETF选动量前3，等权重买入）",
        "timing": "daily",
        "select_fn": "scripts.strategies.v46_etf_rotation.select_stocks_v46",
        "calc_factors_fn": "scripts.strategies.v46_etf_rotation.calc_factors_v46",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 8,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.33,  # 3只ETF等权重，单只上限33%
            "MAX_HOLDINGS": 3,    # 最多持有3只ETF
            "COOLDOWN_DAYS": 0,
            "MOMENTUM_LOOKBACK": 5,
            "MIN_ETFS": 3,
        },
    },

    # ── v45a: 反转策略（买超跌放量反弹）──
    "v45a": {
        "mode": "custom",
        "description": "反转策略（mom_5<-4%超跌放量反弹，zz800范围）",
        "timing": "daily",
        "select_fn": "scripts.strategies.v45a_contrarian.select_stocks_v45a",
        "calc_factors_fn": "scripts.strategies.v45a_contrarian.calc_factors_v45a",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.08,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 8,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MARKET_CAP_MIN": 20,
            "MARKET_CAP_MAX": 200,
            "EXCLUDE_ST": True,
            "EXCLUDE_NEW": True,
            "EXCLUDE_LIMIT_UP": True,
            "EXCLUDE_SUSPENDED": True,
            "REBALANCE_DAY": "daily",
            "MONTHS_EMPTY": [],
        },
    },
    # ── v46a: v39i + 行业动量过滤（P0 待验证）──
    "v46a": {
        "mode": "custom",
        "description": "v39i + 行业动量Top10过滤（预期提升夏普，降低回撤）",
        "timing": "daily",
        "select_fn": "scripts.strategies.v46_industry_filter.select_stocks_v46",
        "params": {
            # v39i 基础参数
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "MARKET_CAP_MIN": 0,
            "MARKET_CAP_MAX": float('inf'),
            "EXCLUDE_ST": True,
            # v46 行业过滤参数
            "INDUSTRY_FILTER": True,
            "INDUSTRY_TOP_N": 10,
            "INDUSTRY_MOM_WEIGHTS": [0.4, 0.3, 0.3],
            # v46 连板因子参数
            "STREAK_FACTOR": True,
            "W_STREAK": 0.05,  # 连板因子权重（小权重加分项）
            # v46 业绩预告因子参数
            "EARNINGS_FILTER": True,       # 排除负面预告10天内个股
            "EARNINGS_WINDOW": 10,         # 负面预告规避天数
            "EARNINGS_POSITIVE_DAYS": 20,  # 正面预告信号窗口
            "W_EARNINGS": 0.03,            # 正面预告加分权重
        },
    },
    # ── v49: 连板动量策略（连板记忆 + 动量确认）──
    "v49": {
        "mode": "custom",
        "description": "连板动量：连板辨识度前30% + 动量确认 + 多因子评分",
        "timing": "daily",
        "select_fn": "scripts.strategies.v49_streak_momentum.select_stocks_v49",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.125,
            "MAX_HOLDINGS": 8,
            "COOLDOWN_DAYS": 0,
            "STREAK_DECAY_DAYS": 252,
            "STREAK_PCTILE": 70,
            "MOM_THRESHOLD": 0.03,
            "MOM_THRESHOLD_BEAR": 0.05,
            "W_STREAK": 0.20,
            "W_MOM": 0.25,
            "W_PV_CORR": 0.05,
            "W_SIZE": 0.20,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v56a: 多空Alpha双引擎（正向聪明钱+反向散户偏差）──
    "v56a": {
        "mode": "custom",
        "description": "多空Alpha双引擎（聪明钱追踪+散户行为偏差反向，筹码+资金流+质量）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v56a_multialpha.select_stocks_v56a",
        "calc_factors_fn": "scripts.strategies.v56a_multialpha.calc_factors",
        "params": {
            "STOP_LOSS": -0.015,
            "TAKE_PROFIT": 0.03,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.03,
            "MAX_HOLDINGS": 8,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.20,
            "COOLDOWN_DAYS": 0,
            "MAX_SAME_PREFIX": 2,
            "W_SMART_Q": 0.18,
            "W_VOLFLOW": 0.18,
            "W_CHIP": 0.12,
            "W_RETAIL": 0.12,
            "W_HERDING": 0.10,
            "W_REVERSAL": 0.05,
            "W_QUALITY": 0.25,
        },
    },
    # ── v58a: 窄震出趋势（波动率压缩+放量突破）──
    "v58a": {
        "mode": "custom",
        "description": "v58a 窄震出趋势（ATR压缩+振幅收窄+放量突破20日高点+均线粘合）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v58a_breakout.select_stocks_v58a",
        "calc_factors_fn": "scripts.strategies.v58a_breakout.calc_breakout_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.15,
            "HOLD_DAYS_MAX": 10,
            "HOLD_DAYS_MIN": 3,
            "HOLD_DAYS_EXTEND": 5,
            "HOLD_DAYS_EXTEND_PNL": 0.10,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "COOLDOWN_DAYS": 0,
            "ATR_COMPRESSION_MAX": 0.6,
            "AMPLITUDE_MAX": 0.15,
            "VOLUME_SURGE_MIN": 2.0,
            "MA_BAND_MAX": 0.02,
            "W_ATR_COMP": 1.0,
            "W_AMP": 1.0,
            "W_VOL_SURGE": 0.5,
            "W_MA_CONV": 0.5,
        },
    },
    # ── v58b: 超跌+资金承接 ──
    "v58b": {
        "mode": "custom",
        "description": "v58b 超跌反弹（跌幅+RSI超卖+资金流入+放量止跌）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v58b_bounce_recovery.select_stocks_v58b",
        "calc_factors_fn": "scripts.strategies.v58b_bounce_recovery.calc_bounce_factors",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.10,
            "HOLD_DAYS_MAX": 5,
            "HOLD_DAYS_MIN": 2,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.05,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "COOLDOWN_DAYS": 0,
            "DROP_10D_MIN": -0.15,
            "DROP_10D_MAX": -0.05,
            "DROP_5D_MAX": -0.03,
            "RSI_14_MAX": 35,
            "FUND_FLOW_MIN": 1.0,
            "VOL_SURGE_MIN": 1.3,
            "W_DROP": 1.0,
            "W_RSI": 0.5,
            "W_FUND_FLOW": 1.0,
            "W_VOL": 0.5,
        },
    },
    # ── v60a: v39g + 行业中性化评分 ──
    "v60a": {
        "mode": "custom",
        "description": "v60a v39g+行业中性化（评分因子行业均值减法）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v60a_industry_neutral.select_stocks_v60a",
        "calc_factors_fn": "scripts.strategies.v60a_industry_neutral.calc_factors_v60a",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "HOLD_DAYS_EXTEND": 3,
            "HOLD_DAYS_EXTEND_PNL": 0.08,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "COOLDOWN_DAYS": 0,
            "MOM_THRESHOLD": 0.03,
            "PV_CORR_10_MIN": -0.5,
            "PV_CORR_20_MIN": 0.0,
            "BOLL_W_MIN": 0.0,
            "W_MOM": 0.10,
            "W_PV_CORR": 0.05,
            "W_TURNOVER": 0.05,
            "W_SIZE": 0.40,
            "W_FUND_FLOW": 0.05,
            "W_GAP": 0.05,
            "W_ILLIQ": 0.20,
        },
    },

    # ── v61a: 换手率+小市值 低流动性溢价策略 ──
    "v61a": {
        "mode": "custom",
        "description": "v61a 换手率5日均值(负向)+市值(负向) 等权评分, 每5天调仓选前5只",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v61a_turnover_size.select_stocks_v61a",
        "calc_factors_fn": "scripts.strategies.v61a_turnover_size.calc_factors_v61a",
        "params": {
            "STOP_LOSS": -0.10,
            "TAKE_PROFIT": 0.20,
            "HOLD_DAYS_MAX": 5,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
        },
    },

    # ── v61b: 换手率+小市值 优化版（止损-8%/止盈+25%/卖出即买） ──
    "v61b": {
        "mode": "custom",
        "description": "v61b 优化风控: 止损-8%/止盈+25%, 卖出即买, WF夏普2.300",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v61b_turnover_size.select_stocks_v61b",
        "calc_factors_fn": "scripts.strategies.v61b_turnover_size.calc_factors_v61b",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 5,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,  # 单个仓位上限20%
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
        },
    },

    # ── v61c: 换手率+小市值 + 到期续持优化 ──
    "v61c": {
        "mode": "custom",
        "description": "v61c 到期续持: 止损-8%/止盈+25%, 到期在Top15内续持, WF夏普2.530",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v61c_turnover_size.select_stocks_v61c",
        "calc_factors_fn": "scripts.strategies.v61c_turnover_size.calc_factors_v61c",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 5,
            "SELL_OUT_OF": 15,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
        },
    },

    # ── v61d: v61c + 放开科创板/北交所 ──
    "v61d": {
        "mode": "custom",
        "description": "v61d: v61c逻辑+含科创板，搭配--no-exclude-star运行",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v61d_turnover_size.select_stocks_v61d",
        "calc_factors_fn": "scripts.strategies.v61d_turnover_size.calc_factors_v61d",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 5,
            "SELL_OUT_OF": 15,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
        },
    },
    # ── v61e: v61c排名掉出Top15 + 涨跌幅确认启动信号 ──
    "v61e": {
        "mode": "custom",
        "description": "v61e 启动信号: v61c排名掉出Top15+涨幅确认, 止损-8%/止盈+25%",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v61e_rank_drop.select_stocks_v61e",
        "calc_factors_fn": "scripts.strategies.v61e_rank_drop.calc_factors_v61e",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 5,
            "SELL_OUT_OF": 15,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
            "RANK_TODAY_N": 15,
            "MIN_RANK_CHANGE": 5,
            "MIN_PCT_3D": 0.01,
            "MIN_PCT_5D": 0.02,
        },
    },

    # ── v74a: 行业动量增强（v61b + 行业动量因子） ──
    "v74a": {
        "mode": "custom",
        "description": "v74a 行业动量增强: 低换手25%+小市值25%+行业动量50%, IC=0.16, IR=0.97",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v74a_industry_momentum.select_stocks_v74a",
        "calc_factors_fn": "scripts.strategies.v74a_industry_momentum.calc_factors_v74a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 5,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
            "W_TURNOVER": 0.25,
            "W_SIZE": 0.25,
            "W_INDUSTRY_MOM": 0.50,
        },
    },

    # ── v75a: 科技趋势增强（锁定科技板块+突破放量+集中持仓） ──
    "v75a": {
        "mode": "custom",
        "description": "v75a 科技趋势增强: 电子/计算机/通信/传媒, 突破45%+放量30%+流动性25%, 持仓3只",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75a_tech_momentum.select_stocks_v75a",
        "calc_factors_fn": "scripts.strategies.v75a_tech_momentum.calc_factors_v75a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "W_BREAKOUT": 0.45,
            "W_VOL_SURGE": 0.30,
            "W_LIQUIDITY": 0.25,
        },
    },

    # ── v75b: 科技趋势增强 + 板块MA50过滤 ──
    "v75b": {
        "mode": "custom",
        "description": "v75b: v75a+板块MA50过滤, 熊市空仓",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75b_bull_tech.select_stocks_v75b",
        "calc_factors_fn": "scripts.strategies.v75b_bull_tech.calc_factors_v75b",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75c: v75a + regime门控（adapter calc_regime） ──
    "v75c": {
        "mode": "custom",
        "description": "v75c: v75a+regime门控, 牛市才交易",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75c_regime_tech.select_stocks_v75c",
        "calc_factors_fn": "scripts.strategies.v75c_regime_tech.calc_factors_v75c",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75d: 连续regime仓位乘数 ──
    "v75d": {
        "mode": "custom",
        "description": "v75d: v75a+连续regime仓位乘数",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75d_continuous_regime.select_stocks_v75d",
        "calc_factors_fn": "scripts.strategies.v75d_continuous_regime.calc_factors_v75d",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75e: 波动率缩放仓位 ──
    "v75e": {
        "mode": "custom",
        "description": "v75e: v75a+波动率缩放仓位",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75e_vol_scaled.select_stocks_v75e",
        "calc_factors_fn": "scripts.strategies.v75e_vol_scaled.calc_factors_v75e",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75f: 市场广度过滤 ──
    "v75f": {
        "mode": "custom",
        "description": "v75f: v75a+市场广度过滤",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75f_breadth.select_stocks_v75f",
        "calc_factors_fn": "scripts.strategies.v75f_breadth.calc_factors_v75f",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75g: v75f + 波动率缩放 ──
    "v75g": {
        "mode": "custom",
        "description": "v75g: v75f+波动率缩放仓位",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75g_combo.select_stocks_v75g",
        "calc_factors_fn": "scripts.strategies.v75g_combo.calc_factors_v75g",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
        },
    },

    # ── v75h: v75f + 因子权重优化（突破0.35/放量0.30/流动0.35） ──
    "v75h": {
        "mode": "custom",
        "description": "v75h: v75f+因子权重优化(0.35/0.30/0.35), 全量回测Sharpe 0.8033",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75h_optimized.select_stocks_v75h",
        "calc_factors_fn": "scripts.strategies.v75h_optimized.calc_factors_v75h",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.35,
            "W_VOL_SURGE": 0.30,
            "W_LIQUIDITY": 0.35,
        },
    },

    # ── v75j: 流动性因子 + 广度过滤（去掉弱因子） ──
    "v75j": {
        "mode": "custom",
        "description": "v75j: 流动性单因子+广度过滤，去掉突破/放量（IC<0.03）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75j_liquidity_only.select_stocks_v75j",
        "calc_factors_fn": "scripts.strategies.v75j_liquidity_only.calc_factors_v75j",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
        },
    },

    # ── v75k: v75j + 纳斯达克隔夜择时 ──
    "v75k": {
        "mode": "custom",
        "description": "v75k: v75j + QQQ隔夜择时，纳指跌>3%不开仓/跌1~3%减半",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75k_nasdaq_timing.select_stocks_v75k",
        "calc_factors_fn": "scripts.strategies.v75k_nasdaq_timing.calc_factors_v75k",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
            "QQQ_GATE_STRONG": -0.03,
            "QQQ_GATE_MILD": -0.01,
        },
    },

    # ── v75l: v75j + QQQ + 广度双择时（OR组合） ──
    "v75l": {
        "mode": "custom",
        "description": "v75l: v75j + QQQ隔夜+广度双择时，任一触发不开仓",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75l_qqq_breadth_combo.select_stocks_v75l",
        "calc_factors_fn": "scripts.strategies.v75l_qqq_breadth_combo.calc_factors_v75l",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
            "QQQ_GATE_STRONG": -0.03,
            "QQQ_GATE_MILD": -0.01,
        },
    },

    # ── v75m: v75j + 分数增速二次排序 ──
    "v75m": {
        "mode": "custom",
        "description": "v75m: v75j + score_delta增速排序，选正在变好的股票",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75m_score_delta.select_stocks_v75m",
        "calc_factors_fn": "scripts.strategies.v75m_score_delta.calc_factors_v75m",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
            "SCORE_DELTA_LOOKBACK": 5,  # 5日增速
        },
    },

    # ── v75n: v75j + 放开科创板/北交所 ──
    "v75n": {
        "mode": "custom",
        "description": "v75n: v75j逻辑+含科创板，搭配--no-exclude-star运行",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75n_no_star_filter.select_stocks_v75n",
        "calc_factors_fn": "scripts.strategies.v75n_no_star_filter.calc_factors_v75n",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
        },
    },

    # ── v84a: v75n + 纯科技板块过滤 ──
    "v84a": {
        "mode": "custom",
        "description": "v84a: 流动性因子限定科技板块+含科创板，搭配--no-exclude-star运行",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v84a_tech_only.select_stocks_v84a",
        "calc_factors_fn": "scripts.strategies.v84a_tech_only.calc_factors_v84a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
        },
    },

    # ── v75p: v75n + 更严格广度择时 ──
    "v75p": {
        "mode": "custom",
        "description": "v75p: 流动性因子+含科创板+更严格广度择时(BREADTH_LOW=0.40)",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75p_breadth_focus.select_stocks_v75p",
        "calc_factors_fn": "scripts.strategies.v75p_breadth_focus.calc_factors_v75p",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.40,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
        },
    },

    # ── v85a: 板块动量+流动性双因子（含科创板） ──
    "v85a": {
        "mode": "custom",
        "description": "v85a: 板块动量+流动性双因子，含科创板，搭配--no-exclude-star运行",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v85a_sector_momentum.select_stocks_v85a",
        "calc_factors_fn": "scripts.strategies.v85a_sector_momentum.calc_factors_v85a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 0.5,
            "W_SECTOR_MOM": 0.5,
            "SECTOR_MOM_WINDOW": 20,
        },
    },

    # ── v85b: 广度动态仓位管理 + v75n选股 ──
    "v85b": {
        "mode": "custom",
        "description": "v85b: 广度动态仓位(MA20>0.6满仓,0.4~0.6线性,0.2~0.4低仓),含科创板",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v85b_dynamic_position.select_stocks_v85b",
        "calc_factors_fn": "scripts.strategies.v85b_dynamic_position.calc_factors_v85b",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_FULL": 0.60,
            "BREADTH_HALF": 0.40,
            "BREADTH_MIN": 0.20,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 1.0,
        },
    },

    # ── v75i: v75f + 因子参数扫描（窗口期优化） ──
    "v75i": {
        "mode": "custom",
        "description": "v75i: v75f+因子参数扫描(窗口期优化), 固定v75f权重",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v75i_factor_param.select_stocks_v75i",
        "calc_factors_fn": "scripts.strategies.v75i_factor_param.calc_factors_v75i",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.30,
            "HOLD_DAYS_MAX": 15,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.45,
            "W_VOL_SURGE": 0.30,
            "W_LIQUIDITY": 0.25,
            "BREAKOUT_WINDOW": 20,
            "VOL_SHORT": 5,
            "VOL_LONG": 20,
            "LIQ_WINDOW": 20,
        },
    },

    # ── v76a: v61b+v75a 组合策略（60/40攻守兼备） ──
    "v76a": {
        "mode": "custom",
        "description": "v76a 组合: v61b*60%+v75a*40%, 攻守兼备",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v76a_combo.select_stocks_v76a",
        "calc_factors_fn": "scripts.strategies.v76a_combo.calc_factors_v76a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 10,
            "MAX_DAILY_BUY": 5,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 5,
            "REBALANCE_DAYS": 5,
            "W_V61B": 0.60,
            "W_V75A": 0.40,
        },
    },

    # ── v81: IVOL低波溢价因子（外部因子验证） ──
    "v81": {
        "mode": "custom",
        "description": "v81 IVOL低波溢价: 特质波动率因子+广度过滤",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v81_ivol.select_stocks_v81",
        "calc_factors_fn": "scripts.strategies.v81_ivol.calc_factors_v81",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "IVOL_WINDOW": 20,
        },
    },

    # ── v70: 中盘域动量策略（100-500亿市值） ──
    "v70": {
        "mode": "custom",
        "description": "v70 中盘域动量: 动量20%+质量20%+低波20%+反转40%, 针对100-500亿市值",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v62_midcap_momentum.select_stocks_v70",
        "calc_factors_fn": "scripts.strategies.v62_midcap_momentum.calc_factors_v70",
        "params": {
            "STOP_LOSS": -0.06,
            "TAKE_PROFIT": 0.12,
            "HOLD_DAYS_MAX": 5,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 4,
            "MOM_THRESHOLD": -0.10,
            "MIN_MARKET_CAP": 100e8,
            "MAX_MARKET_CAP": 500e8,
            "W_MOM": 0.20,
            "W_QUALITY": 0.20,
            "W_LOW_VOL": 0.20,
            "W_REVERSAL": 0.40,
        },
    },

    # ── v39g_sentiment: v39g + 舆情因子 ──
    "v39g_sentiment": {
        "mode": "custom",
        "description": "v39g + 舆情动量（负向：情绪越高→扣分）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v39g_sentiment.select_stocks_v39g_sentiment",
        "calc_factors_fn": "scripts.strategies.v39g_sentiment.calc_factors_v39g_sentiment",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "MAX_DAILY_BUY": 4,
            "MAX_POSITION": 0.20,
            "MAX_HOLDINGS": 5,
            "MOM_THRESHOLD": 0.03,
            "W_MOM": 0.10,
            "W_SIZE": 0.35,
            "W_ILLIQ": 0.20,
            "W_SENTIMENT": -0.15,
        },
    },
    # ── v63_dragon_leader: 龙头战法（二板定龙头）──
    "v63_dragon_leader": {
        "mode": "custom",
        "description": "v80 龙头战法（二板定龙头，追求主升浪）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v63_dragon_leader.select_stocks_v63_dragon",
        "calc_factors_fn": "scripts.strategies.v63_dragon_leader.calc_factors_v63_dragon",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "MAX_DAILY_BUY": 2,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 3,
            "MIN_STREAK": 2,
            "W_STREAK": 0.40,
            "W_SECTOR": 0.30,
            "W_SENTIMENT": 0.20,
            "W_LIQUIDITY": 0.10,
        },
    },
    # ── v64_concept_heat: 概念热度打板 ──
    "v64_concept_heat": {
        "mode": "custom",
        "description": "v81 概念热度打板（强势板块+近期涨停）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v64_concept_heat.select_stocks_v64_concept",
        "calc_factors_fn": "scripts.strategies.v64_concept_heat.calc_factors_v64_concept",
        "params": {
            "STOP_LOSS": -0.05,
            "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 3,
            "MAX_DAILY_BUY": 2,
            "MAX_POSITION": 0.25,
            "MAX_HOLDINGS": 3,
            "MIN_RECENT_LIMIT": 1,
            "CONCEPT_HEAT_TOP": 0.02,
            "W_CONCEPT_HEAT": 0.40,
            "W_RECENT_LIMIT": 0.30,
            "W_LIQUIDITY": 0.20,
            "W_MARKET_CAP": 0.10,
        },
    },

    # ── v65_yesterday_limit: 昨日涨停打板（日频）──
    "v65_yesterday_limit": {
        "mode": "custom",
        "description": "v65 昨日涨停打板（连续涨停+强势概念+次日高开）",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v65_yesterday_limit.select_stocks_v65_yesterday_limit",
        "calc_factors_fn": "scripts.strategies.v65_yesterday_limit.calc_factors_v65_yesterday_limit",
        "params": {
            "STOP_LOSS": -0.05, "TAKE_PROFIT": 0.05,
            "HOLD_DAYS_MAX": 1, "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.20, "MAX_HOLDINGS": 5,
            "MIN_STREAK": 2, "HIGH_OPEN_THRESHOLD": 0.02,
            "CONCEPT_HEAT_TOP": 0.98,
            "W_STREAK": 0.40, "W_CONCEPT_HEAT": 0.30,
            "W_LIQUIDITY": 0.20, "W_HIGH_OPEN": 0.10,
        },
    },

    # ── v86a: 5日EMA因子 + 广度过滤（Factor Factory第二批） ──
    "v86a": {
        "mode": "custom",
        "description": "v86a: 5日EMA反向排名+广度过滤，替代v75j的流动性因子",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v86a_ema5.select_stocks_v86a",
        "calc_factors_fn": "scripts.strategies.v86a_ema5.calc_factors_v86a",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 0.0,
            "W_EMA": 1.0,
            "EMA_WINDOW": 5,
        },
    },

    # ── v86b: 资金流量因子 + 广度过滤（Factor Factory第二批） ──
    "v86b": {
        "mode": "custom",
        "description": "v86b: 20日资金流量反向排名+广度过滤，替代v75j的流动性因子",
        "timing": "intraday",
        "select_fn": "scripts.strategies.v86b_money_flow.select_stocks_v86b",
        "calc_factors_fn": "scripts.strategies.v86b_money_flow.calc_factors_v86b",
        "params": {
            "STOP_LOSS": -0.08,
            "TAKE_PROFIT": 0.25,
            "HOLD_DAYS_MAX": 20,
            "MAX_DAILY_BUY": 3,
            "MAX_POSITION": 0.35,
            "MAX_HOLDINGS": 3,
            "REBALANCE_DAYS": 10,
            "MAX_STOCK_PRICE": 300,
            "BREADTH_MA": 20,
            "BREADTH_HIGH": 0.50,
            "BREADTH_LOW": 0.30,
            "W_BREAKOUT": 0.0,
            "W_VOL_SURGE": 0.0,
            "W_LIQUIDITY": 0.0,
            "W_MONEY_FLOW": 1.0,
            "MONEY_FLOW_WINDOW": 20,
        },
    },
}
